// packages/web-components/src/HButton.js
const template = document.createElement('template');
template.innerHTML = `
  <style>
    button {
      font-size: 16px;
      color: #182633;
      background: #ffffff;
      padding: 4px 16px;
      border: 2px solid #2a4158;
      border-radius: 4px;
      font-family: sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      text-align: center;
    }
    button:hover {
      cursor: pointer;
    }
    button:focus {
      outline: none;
      box-shadow: 0 0 3px #958a56;
    }
  </style>
  <button type="button">
    <slot />
  </button>
`;

class HButton extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({mode: 'open'});
    this.shadowRoot.appendChild(template.content.cloneNode(true));
  }

  connectedCallback() {
    if (!this.hasAttribute('type'))
      this.setAttribute('type', 'button');

    if (!this.hasAttribute('tabindex'))
      this.setAttribute('tabindex', 0);
  }
}

window.customElements.define('h-button', HButton);

// packages/vue/src/HButton.vue
<template>
  <button class="h-button" type="button" >
    <slot />
  </button>
</template>

<script>
export default {
  name: 'HButton',
}
</script>

<style src="@hydra/tokens/src/tokens.css">
</style>
<style>
.h-button {
  color: var(--primary-color);
  background: #ffffff;
  padding: var(--size-xs) var(--size-m);
  border: 2px solid var(--primary-color);
  border-radius: 4px;
  font-family: sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
}
</style>
